name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dev
    pull_request:
      branches:
        - main
        - dev

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Install Prisma and NestJS dependencies
        run: |
          cd backend
          yarn install
        working-directory: .

      - name: Run backend tests
        run: |
          cd backend
          yarn run test
        working-directory: .
